### ISSUE TITLE
Node Uploader: Investigate Fix upload exception

### ISSUE THREAD

**Issue by cspindler** [mitwelten/mitwelten-ml-backend#13]
```log
Aug 06 05:17:04 host python[11359]: File upload error Expecting value: line 1 column 1 (char 0)
```

It seems like the file get's uploaded but there's an error at the end?

__file_uploaded_at matches__: 1659759424 = Aug 06 05:17:04 BST

record from `file_index.db`:

| attribute | value |
| - | - |
| file_id | 11871 |
| path | /mnt/elements/1967-0514/2022-05-22/13/1967-0514_2022-05-22T13-12-25Z.jpg |
| sha256 | 8999528d6704d6d11ca073c4555871e9dae425c4a3bef2640dfbe248a4c96774 |
| state | -4 |
| timestamp | 2022-05-22 13:12:25+00:00 |
| indexed_at | 1659641810 |
| checked_at | 1659645185 |
| meta_uploaded_at | null |
| file_uploaded_at | 1659759424 |

**Comment by cspindler** [comment]
```log
Aug 10 01:26:30 host python[585]: File upload error Expecting value: line 1 column 1 (char 0)
Aug 10 01:26:30 host python[585]: Traceback (most recent call last):
Aug 10 01:26:30 host python[585]:   File "/home/pi/mitwelten-ml-backend/ingest/uploader/.venv/lib/python3.7/site-packages/requests/models.py", line 971, in json
Aug 10 01:26:30 host python[585]:     return complexjson.loads(self.text, **kwargs)
Aug 10 01:26:30 host python[585]:   File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
Aug 10 01:26:30 host python[585]:     return _default_decoder.decode(s)
Aug 10 01:26:30 host python[585]:   File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
Aug 10 01:26:30 host python[585]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Aug 10 01:26:30 host python[585]:   File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
Aug 10 01:26:30 host python[585]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Aug 10 01:26:30 host python[585]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Aug 10 01:26:30 host python[585]: During handling of the above exception, another exception occurred:
Aug 10 01:26:30 host python[585]: Traceback (most recent call last):
Aug 10 01:26:30 host python[585]:   File "uploader_node.py", line 277, in worker
Aug 10 01:26:30 host python[585]:     raise MetadataInsertException(f"failed to insert metadata for {d['path']}: {r.json()['detail']}")
Aug 10 01:26:30 host python[585]:   File "/home/pi/mitwelten-ml-backend/ingest/uploader/.venv/lib/python3.7/site-packages/requests/models.py", line 975, in json
Aug 10 01:26:30 host python[585]:     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
Aug 10 01:26:30 host python[585]: requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
